server:
  port: 8070

spring:
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 60000
        filters: stat,wall
      primary: jww #设置默认的数据源
      datasource:
        jww:
          username: ENC(9rNHpsWlZ+r2l6oHdlwh0A==)
          password:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/jww
        jww2:
          username: root
          password:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/jww2
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 1
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  path: D:\tmp
  level:
    root: info
    com.rrx: debug

jasypt:
  encryptor:
    password: ${jssyptpwd}

curator:
    connectString: 127.0.0.1:2181  # zookeeper地址
    connectionTimeoutMs: 5000 # 连接超时时间
    elapsedTimeMs: 5000 #重试间隔时间
    retryCount: 5  #重试次数
    sessionTimeoutMs: 60000 # session超时时间

elastic:
      job:
        zk:
            namespace: kaoqin_job1
            serverLists: 127.0.0.1:2181
        MySimpleJob:
            cron: 0 0 * * * ? *
            description: simple job
            disabled: false
            failover: true
            #jobExceptionHandler: com.rrx.kaoqins.core.config.elasticjob.CustomJobExceptionHandler
            jobParameter: test
            #listener: com.rrx.kaoqins.core.config.elasticjob.MessageElasticJobListener
            misfire: true
            monitorExecution: false
            overwrite: true
            shardingTotalCount: 2
            shardingItemParameters: 0=A,1=B



# debug: true
#sharding:
#    jdbc:
#        data-sources:
#            ds_master:
#                driver-class-name: com.mysql.jdbc.Driver
#                jdbc-url: jdbc:mysql://localhost:3306/jww?useUnicode=true&characterEncoding=utf-8&useSSL=true
#                password:
#                username: root